language: c

compiler: gcc

sudo: require

service:
  - docker

git:
  depth: false

## NOTIFICATIONS
notifications:
  email:
    recipients:
    - florent.poinsard@epitech.eu
    on_success: never
    on_failure: always
  slack: epitech-tls-22:OsWtUSdnX45sPtL2EbBPO8aA

jobs:
    include :
        - stage: build
          name: "Build"
          install:
            - docker pull epitechcontent/epitest-docker
          script:
            - docker run -v $PWD:/app epitechcontent/epitest-docker bash -c "cd app"

        - stage: tests
          name: "Unit Tests"
          install:
            - docker pull epitechcontent/epitest-docker
          script:
            - docker run -v $PWD:/app epitechcontent/epitest-docker bash -c "cd app"
        -
          name: "Functional Tests"
          if: branch IN (master, dev, tests)
          before_script:
            - docker pull epitechcontent/epitest-docker
          script:
            - docker run -v $PWD:/app epitechcontent/epitest-docker bash -c "cd app && make tests_functional || echo no functional test yet"

        - stage: deploy
          name: "Deployement"
          if: branch IN (master, travis) AND type != cron AND type != pull_request
          before_script:
            - ssh-keyscan git.epitech.eu >> ~/.ssh/known_hosts
            - git checkout $TRAVIS_BRANCH
          script:
            - git push --repo=git@git.epitech.eu:/florent.poinsard@epitech.eu/PSU_2018_nmobjdump --force
